# name: Deploy-Cloud_run

# on:
#   push:
#     branches: [ main ]

# jobs:
#   job_id:
#     permissions:
#       contents: 'read'
#       id-token: 'write'

#     steps:
#     - id: 'auth'
#       uses: 'google-github-actions/auth@v0'
#       with:
#         workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
#         service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

#     - id: 'deploy'
#       uses: 'google-github-actions/deploy-cloudrun@v0'
#       with:
#         service: 'hello-cloud-run'
#         image: 'gcr.io/cloudrun/hello'

#     - name: 'Use output'
#       run: 'curl "${{ steps.deploy.outputs.url }}"'
